version: '3.3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build:
      context: flask_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: gunicorn --timeout=120 --workers=1 --bind=0.0.0.0:8000 wsgi:server

  nginx:
    container_name: nginx
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask_app